name: Create Artifact in Generic JFrog

on: [push]

jobs:
  
  build:
    env:
      version: v0.0.0.${{github.run_id}}
    runs-on: ubuntu-latest
     
    
    steps:
    - name: Checkout in self-hosted runner
      uses: actions/checkout@v3
    
    - name: Print a Hello workflow   
      run: echo "Hello workflow!"

    - name: Create a zip file
      run: git archive --format=zip --output=${{env.version}}.zip main lib
      
    - name: Push the corresponding artifact to JFrog
      run: curl -H "X-JFrog-Art-Api:${{ secrets.JF_ARTIFACTORY_API_KEY }}" -T ${{env.version}}.zip "https://luistorrescisneros.jfrog.io/artifactory/default-generic-local/${{github.repository}}/${{env.version}}.zip"

    
